dist: bionic

language: cpp
compiler: clang

addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-7
    packages:
      - libgpiod-dev
      - clang-7
      - libc++abi-7-dev
      - libc++-7-dev
      - g++-8


script:
  - clang++ fanshim_driver.cpp -o fanshim_driver -O3 -std=c++17 -lstdc++fs -lgpiodcxx
