dist: bionic

language: cpp
compiler: gcc

addons:
  apt:
    source:
    - ubuntu-toolchain-r-test
    packages:
    - libgpiod-dev
    - gcc-8
    - libc++abi-dev
    - libc++-dev


script:
  - g++ fanshim_driver.cpp -o fanshim_driver -O3 -std=c++17 -lstdc++fs -lgpiodcxx
